version: '2'
services:
    lunchapplicationdg-app:
        image: lunchapplicationdg
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@lunchapplicationdg-oracle:1521:LunchApplicationDG
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 7777:7777
